const collection = [
  {
    id: 1,
    model: "Jack & Danny D160S",
    desc: "lorem ipsum",
    img: "./img/guitar1.png",
    cost: 7800,
    isNotBelong: true,
  },
  {
    id: 2,
    model: "Paramount F-550BCEQN",
    desc: "lorem ipsum",
    img: "./img/guitar2.png",
    cost: 3100,
    isNotBelong: true,
  },
  {
    id: 3,
    model: "Mclorence MC138",
    desc: "lorem ipsum",
    img: "./img/guitar3.png",
    cost: 4000,
    isNotBelong: true,
  },
  {
    id: 4,
    model: "Ephiphone Special II",
    desc: "lorem ipsum",
    img: "./img/guitar4.png",
    cost: 6300,
    isNotBelong: true,
  },
  {
    id: 5,
    model: "Future SG-45",
    desc: "lorem ipsum",
    img: "./img/guitar5.png",
    cost: 7000,
    isNotBelong: true,
  },
  {
    id: 6,
    model: "Gibson Les Paul Standard '50s",
    desc: "lorem ipsum",
    img: "./img/guitar6.png",
    cost: 85000,
    isNotBelong: false,
  },
  {
    id: 7,
    model: "Fender Stratocaster American Original '50s",
    desc: "lorem ipsum",
    img: "./img/guitar7.png",
    cost: 72000,
    isNotBelong: false,
  },
  {
    id: 8,
    model: "Maison LP38",
    desc: "lorem ipsum",
    img: "./img/guitar8.png",
    cost: 12000,
    isNotBelong: true,
  },
  {
    id: 9,
    model: "Gibson Les Paul Gothic Morte",
    desc: "lorem ipsum",
    img: "./img/guitar9.png",
    cost: 40000,
    isNotBelong: false,
  },
  {
    id: 10,
    model: 'Fender Telecaster "3xbun" Signature',
    desc: "lorem ipsum",
    img: "./img/guitar10.png",
    cost: 80000,
    isNotBelong: false,
  },
  {
    id: 11,
    model: 'Fender Telecaster "Jim Root" Signature',
    desc: "lorem ipsum",
    img: "./img/guitar11.png",
    cost: 47000,
    isNotBelong: true,
  },
  {
    id: 12,
    model: 'Gibson SG 2013 "The Great Wave"',
    desc: "lorem ipsum",
    img: "./img/guitar12.png",
    cost: 24000,
    isNotBelong: false,
  },
  {
    id: 13,
    model: 'Paramount Flying V "Ouija Board"',
    desc: "lorem ipsum",
    img: "./img/guitar13.png",
    cost: 8000,
    isNotBelong: false,
  },
  {
    id: 14,
    model: "Gibson Les Paul Signature T Gold Series",
    desc: "lorem ipsum",
    img: "./img/guitar14.png",
    cost: 58000,
    isNotBelong: false,
  },
  {
    id: 15,
    model: "Spear RD-W",
    desc: "lorem ipsum",
    img: "./img/guitar15.png",
    cost: 8500,
    isNotBelong: false,
  },
];

export default collection;
